# Generated by Django 5.1.6 on 2025-02-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedUser', models.JSONField()),
                ('assignedUserFullName', models.JSONField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dueDate', models.DateField()),
                ('listType', models.CharField(max_length=50)),
                ('prio', models.CharField(max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('subtasks', models.JSONField(default=list)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('firstLetters', models.CharField(max_length=3)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
